CC = gcc -Wall 

w1:
	$(CC) worker1.c -o worker1

w2:
	$(CC) worker2.c -o worker2

w3:
	$(CC) worker3.c -o worker3

m: 
	$(CC) main.c -o main

all:
	$(CC) worker1.c -o worker1
	$(CC) worker2.c -o worker2
	$(CC) worker3.c -o worker3
	$(CC) main.c -o main